name: meiro
base: core22
version: '1.0.0'
summary: Terminal-based maze generation and solving game
description: |
  Meiro is a terminal-based maze game featuring multiple generation algorithms
  including Recursive Backtracking, Kruskal's MST, and Prim's MST.
  Navigate through randomly generated mazes using WASD keys or arrow keys.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
    build-for: amd64

apps:
  meiro:
    command: bin/meiro
    plugs:
      - terminal-support

parts:
  meiro:
    plugin: dump
    source: https://github.com/k1-c/meiro/releases/download/v1.0.0/meiro-linux-x86_64.tar.gz
    stage-packages:
      - libc6
      - libgmp10
    organize:
      meiro: bin/meiro